spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/h2/portfolio;AUTO_SERVER=true
    username: admin
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create